// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.gql.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers =
    (Serializers().toBuilder()
          ..add(FetchPolicy.serializer)
          ..add(GActivatePinData.serializer)
          ..add(GActivatePinData_activatePin.serializer)
          ..add(GActivatePinData_activatePin_user.serializer)
          ..add(GActivatePinReq.serializer)
          ..add(GActivatePinVars.serializer)
          ..add(GChangePasswordData.serializer)
          ..add(GChangePasswordData_changePassword.serializer)
          ..add(GChangePasswordData_changePassword_user.serializer)
          ..add(GChangePasswordReq.serializer)
          ..add(GChangePasswordVars.serializer)
          ..add(GDisablePinData.serializer)
          ..add(GDisablePinData_disablePin.serializer)
          ..add(GDisablePinData_disablePin_user.serializer)
          ..add(GDisablePinReq.serializer)
          ..add(GDisablePinVars.serializer)
          ..add(GForgetPasswordData.serializer)
          ..add(GForgetPasswordData_forgetPassword.serializer)
          ..add(GForgetPasswordData_forgetPassword_user.serializer)
          ..add(GForgetPasswordReq.serializer)
          ..add(GForgetPasswordVars.serializer)
          ..add(GGetUserByTokenData.serializer)
          ..add(GGetUserByTokenData_getUserByToken.serializer)
          ..add(GGetUserByTokenData_getUserByToken_user.serializer)
          ..add(GGetUserByTokenReq.serializer)
          ..add(GGetUserByTokenVars.serializer)
          ..add(GLoginUserData.serializer)
          ..add(GLoginUserData_loginUser.serializer)
          ..add(GLoginUserData_loginUser_user.serializer)
          ..add(GLoginUserReq.serializer)
          ..add(GLoginUserVars.serializer)
          ..add(GLoginWithPinData.serializer)
          ..add(GLoginWithPinData_loginWithPin.serializer)
          ..add(GLoginWithPinData_loginWithPin_user.serializer)
          ..add(GLoginWithPinReq.serializer)
          ..add(GLoginWithPinVars.serializer)
          ..add(GRegisterUserData.serializer)
          ..add(GRegisterUserData_registerUser.serializer)
          ..add(GRegisterUserData_registerUser_user.serializer)
          ..add(GRegisterUserReq.serializer)
          ..add(GRegisterUserVars.serializer)
          ..add(GResetPinData.serializer)
          ..add(GResetPinData_resetPin.serializer)
          ..add(GResetPinData_resetPin_user.serializer)
          ..add(GResetPinReq.serializer)
          ..add(GResetPinVars.serializer)
          ..add(GSetPinData.serializer)
          ..add(GSetPinData_setPin.serializer)
          ..add(GSetPinData_setPin_user.serializer)
          ..add(GSetPinReq.serializer)
          ..add(GSetPinVars.serializer)
          ..add(GVerifyPinStatusData.serializer)
          ..add(GVerifyPinStatusData_verifyPinStatus.serializer)
          ..add(GVerifyPinStatusReq.serializer)
          ..add(GVerifyPinStatusVars.serializer))
        .build();

// ignore_for_file: deprecated_member_use_from_same_package,type=lint
